home:
   path: /
   controller: App\Controller\HomeController::home


crud:
  path: /projetos/crud
  controller: App\Controller\UsuarioController::index

projetos:
   path: /projetos
   controller: App\Controller\ProjetosController::index

calculadora:
   path: /projetos/calculadora
   controller: App\Controller\ProjetosController::calculadora